module.exports = [
    ["Java", 5],
    // ["C/C++", 3.5],
    ["Golang", 4],
    ["Python", 4],
    ["Linux", 4],
    ["JavaScript", 5],
    ["Bash", 3],
    ["Groovy", 4],
    ["NodeJS", 3],
    ["SQL", 5],
    ["Docker", 5],
    ["Kubernetes", 3],
    ["Vagrant", 2],
    ["OOP", 4],
    ["Web Development", 5],
    ["Reactive Programming", 3],
    ["Multithreading", 4],
    ["Maven", 3],
    ["Gradle", 4],
    ["EJB", 2],
    ["Spring", 4],
    ["JUnit", 4],
    ["Unit Tests", 5],
    ["Hibernate", 4],
    ["JOOQ", 4],
    ["Angular", 4],
    ["ReactJS", 3],
    ["ExtJS", 4],
    ["JQuery", 4],
    ["Action Script", 3],
    ["Flex", 3],
    ["MySQL", 3],
    ["PostgreSQL", 4],
    ["MongoDB", 3],
    ["Redis", 3],
    ["Oracle", 2],
    ["Rabbit MQ", 3],
    ["CI/CD", 4],
    ["OWASP", 4],
    ["AWS", 4],
    ["Cloud Computing", 3],
    ["Tomcat", 4],
    ["Netty", 3],
    ["NGinx", 2],
    ["Helm", 3],
    ["SOLID", 3],
];